---
title: "DetailedManuscriptRevisions"
author: "Shannon Rankin"
date: "`r Sys.Date()`"
output: pdf_document
---

To the Editors of Ecological Informatics:

Thank you for your consideration and review of my research article submission entitled "Open-Source machine learning BANTER acoustic classification of beaked whale echolocation pulses". I appreciate your time and the feedback to improve this manuscript for publication. We agree with all comments and suggestions provided by the reviewers/editors, and we provide an explanation of how we addressed each comment.

-   ***Request to include 3-5 Research Highlights (optional).*** We suggest the following Research Highlights:

    -   BANTER is an open source, accessible machine learning classifier for data with multiple call types

    -   BANTER can use multiple detectors on single call types for acoustic event classification

    -   BANTER can classify beaked whale species with relatively low sample sizes

    -   BANTER is easy to use and can be easily adopted to address current classification needs

-   ***Request to include expanded review of research on the research topic (Introduction).*** Our intention was to focus on a new application of an existing tool, and I assume the request was in relation to relatively new deep learning methods for acoustic classification. To that end, I have included an additional Introduction paragraph that includes consideration of these methods and a justification of why despite the incredible advances in deep learning in recent years, consideration of machine learning methods (such as models based on Random Forest) may be preferred for some classification tasks.

-   ***Request to evaluate our results and draw parallels with relevant studies in the peer reviewed literature to provide important context (Discussion)*****.** In order to provide additional context in the discussion without losing sight of the more narrow goals of this study, I focused on discussion points related specifically to acoustic classification of beaked whales. To that end, I first added a paragraph outlining some specific needs as it relates to acoustic classification of beaked whales. I then provided a comparison of our general results to those provided by other automated methods for acoustic classification of beaked whales providing context regarding the specific needs outlined in the previous paragraph (most importantly, considering all relevant species in a region, including species with low sample sizes). Finally, I modified the final paragraph to acknowledge that the limitations in deep learning methods are most likely temporary, and that the methods provided here can be readily adopted now to meet existing acoustic classification needs.

-   ***Improve Resolution of Figures.*** I have increased the font size on most of the graphs, which required introducing an angle for the x-axis for the heatmaps (c) for all Figures. The page layout for these figures was shifted to Landscape to allow for the wide image format. If additional modifications (minor or major) are needed, these can be accommodated.

-   ***Research Elements (optional).*** This project is a collaboration, and as such not all researchers are fully prepared to make their data publicly available. The data provided my my research lab (epacific in this study) will be publicly available on Figshare (I am only waiting for final acceptance of this paper). This manuscript, and the associated data products will be made publicly available on github (if not in whole, at least the epacific component). We strongly believe in Open Science and strive towards that goal.

I hope that these revisions are acceptable, and that you accept this draft manuscript for publication. If you require additional revisions, I will be happy to consider them. I greatly appreciate you and your team for your time and energy considering this manuscript for publication.

Sincerely,

Shannon Rankin

Wildlife Research Biologist

Southwest Fisheries Science Center

NOAA Fisheries
